Standardized spacing
Change-Id: I326d77d4f27f48956862de9dac16c1544fd749fe

diff --git a/githooks/commit-msg b/githooks/commit-msg
--- a/githooks/commit-msg
+++ b/githooks/commit-msg
@@ -19,31 +19,31 @@
 
 set -u
 
-# avoid [[ which is not POSIX sh.
+# Avoid [[ which is not POSIX sh.
 if test "$#" != 1 ; then
-  echo "$0 requires an argument."
-  exit 1
+    echo "$0 requires an argument."
+    exit 1
 fi
 
 if test ! -f "$1" ; then
-  echo "file does not exist: $1"
-  exit 1
+    echo "file does not exist: $1"
+    exit 1
 fi
 
-# Do not create a change id if requested
+# Do not create a change id if requested.
 if test "false" = "$(git config --bool --get gerrit.createChangeId)" ; then
-  exit 0
+    exit 0
 fi
 
 # Do not create a change id for squash commits.
 if head -n1 "$1" | grep -q '^squash! '; then
-  exit 0
+    exit 0
 fi
 
 if git rev-parse --verify HEAD >/dev/null 2>&1; then
-  refhash="$(git rev-parse HEAD)"
+    refhash="$(git rev-parse HEAD)"
 else
-  refhash="$(git hash-object -t tree /dev/null)"
+    refhash="$(git hash-object -t tree /dev/null)"
 fi
 
 random=$({ git var GIT_COMMITTER_IDENT ; echo "$refhash" ; cat "$1"; } | git hash-object --stdin)
@@ -52,37 +52,37 @@ dest="$1.tmp.${random}"
 trap 'rm -f "$dest" "$dest-2"' EXIT
 
 if ! git stripspace --strip-comments < "$1" > "${dest}" ; then
-   echo "cannot strip comments from $1"
-   exit 1
+    echo "cannot strip comments from $1"
+    exit 1
 fi
 
 if test ! -s "${dest}" ; then
-  echo "file is empty: $1"
-  exit 1
+    echo "file is empty: $1"
+    exit 1
 fi
 
 reviewurl="$(git config --get gerrit.reviewUrl)"
 if test -n "${reviewurl}" ; then
-  token="Link"
-  value="${reviewurl%/}/id/I$random"
-  pattern=".*/id/I[0-9a-f]\{40\}$"
+    token="Link"
+    value="${reviewurl%/}/id/I$random"
+    pattern=".*/id/I[0-9a-f]\{40\}$"
 else
-  token="Change-Id"
-  value="I$random"
-  pattern=".*"
+    token="Change-Id"
+    value="I$random"
+    pattern=".*"
 fi
 
 if git interpret-trailers --parse < "$1" | grep -q "^$token: $pattern$" ; then
-  exit 0
+    exit 0
 fi
 
 # There must be a Signed-off-by trailer for the code below to work. Insert a
 # sentinel at the end to make sure there is one.
 # Avoid the --in-place option which only appeared in Git 2.8
 if ! git interpret-trailers \
-         --trailer "Signed-off-by: SENTINEL" < "$1" > "$dest-2" ; then
-  echo "cannot insert Signed-off-by sentinel line in $1"
-  exit 1
+        --trailer "Signed-off-by: SENTINEL" < "$1" > "$dest-2" ; then
+    echo "cannot insert Signed-off-by sentinel line in $1"
+    exit 1
 fi
 
 # Make sure the trailer appears before any Signed-off-by trailers by inserting
@@ -94,11 +94,11 @@ if ! git -c trailer.where=before interpret-trailers \
          --trailer "Signed-off-by: $token: $value" < "$dest-2" |
      sed -e "s/^Signed-off-by: \($token: \)/\1/" \
          -e "/^Signed-off-by: SENTINEL/d" > "$dest" ; then
-  echo "cannot insert $token line in $1"
-  exit 1
+    echo "cannot insert $token line in $1"
+    exit 1
 fi
 
 if ! mv "${dest}" "$1" ; then
-  echo "cannot mv ${dest} to $1"
-  exit 1
+    echo "cannot mv ${dest} to $1"
+    exit 1
 fi
